pipeline:
  # integration:
  #   image: python:2
  #   commands:
  #     - echo "Building"

  delivery:
    image: plugins/docker
    repo: hpreston/myhero_spark
    tags: "${DRONE_COMMIT_BRANCH}"
    secrets: [ docker_username, docker_password ]

  deliveryprod:
    image: plugins/docker
    repo: hpreston/myhero_spark
    tag: latest
    when:
      branch: master
    secrets: [ docker_username, docker_password ]

  notify:
    image: hpreston/drone-spark:0.7
    secrets: [ SPARK_TOKEN, PERSONEMAIL ]
    message: "Build Complete!"
    when:
      status: [ success, failure ]
